def generar_sql(descripcion):
    # Dividimos el string en líneas
    lineas = descripcion.strip().splitlines()

    # Tomamos la primera línea como los nombres de las columnas
    columnas = lineas[0].split("\t")

    # Inicializamos una lista para almacenar las consultas generadas
    consultas_sql = []
    plantilla_insert = "INSERT INTO clases ({}) VALUES ({});\n"

    for linea in lineas[1:]:
        valores = linea.split("\t")

        # Creamos el string de columnas, envolviendo los nombres de columnas con corchetes
        columnas_str = ", ".join([f"[{col.lower().replace(' ', '_')}]" for col in columnas])

        # Creamos el string de valores (añadiendo comillas simples si hay espacios en los valores)
        valores_str = []
        for valor in valores:
            valor_limpio = valor.strip()
            # Envolver en comillas simples si tiene espacios o es tipo CHAR
            if " " in valor_limpio or not valor_limpio.isdigit():
                if valor_limpio == '':
                    valores_str.append("NULL")  # Tratamos los valores vacíos como NULL
                else:
                    valores_str.append(f"'{valor_limpio}'")
            else:
                valores_str.append(valor_limpio)

        # Unimos los valores en un string
        valores_str = ", ".join(valores_str)

        # Añadimos la consulta SQL a la lista
        consultas_sql.append(plantilla_insert.format(columnas_str, valores_str))

    # Guardamos las consultas generadas en un archivo .sql con codificación UTF-8
    with open("output.sql", "w", encoding="utf-8") as archivo_sql:
        archivo_sql.writelines(consultas_sql)


# Ejemplo de uso
descripcion = """
clase	caracteristica	denominacion	tipo_campo	ctd_posiciones	decimales	unidad
BOMBAS	AMPERAJE	AMPERAJE	NUM	6	2	A
BOMBAS	CABEZA_DE_SUCCION	CABEZA DE SUCCION	NUM	8	0	m
BOMBAS	CAUDAL_LPM	CAUDAL EN l/min	NUM	6	2	      
BOMBAS	DIAMETRO_DESCARGA	DIAMETRO DESCARGA	NUM	4	2	mm
BOMBAS	DIAMETRO_EJE	DIAMETRO EJE	NUM	6	2	mm
BOMBAS	DIAMETRO_SUCCION	DIAMETRO SUCCION	NUM	5	3	Pulg.
BOMBAS	ETAPAS	ETAPAS	NUM	2	0	      
BOMBAS	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
BOMBAS	POTENCIA_HP	POTENCIA HP	NUM	6	2	      
BOMBAS	PRESION_DE_SERVICIO	PRESION DE SERVICIO	NUM	6	2	psi
BOMBAS	PRESION_DESCARGA_BAR	PRESION DESCARGA BAR	NUM	6	2	bar
BOMBAS	PRESION_SUCCION	PRESION SUCCION	NUM	6	2	bar
BOMBAS	REF_RODAMIENTO	REFERENCIA DE RODAMIENTO	CHAR	25	0	      
BOMBAS	RPM	RPM	NUM	9	2	rpm
BOMBAS	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
BOMBAS	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
BOMBAS	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	      
BOMBAS	TIPO_BOMBA	TIPO BOMBA	CHAR	25	0	      
BOMBAS	TIPO_DE_IMPULSION	TIPO DE IMPULSION	CHAR	20	0	      
BOMBAS	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
BOMBAS	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
BOMBAS	TIPO_SELLO	TIPO SELLO	CHAR	20	0	      
BOMBAS	VOLTAJE	Voltaje	NUM	6	2	V
BOMBAS	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
ARMAS_NAVALES	ALCANCE_EFECTIVO	ALCANCE EFECTIVO	NUM	12	2	m
ARMAS_NAVALES	ALCANCE_MAXIMO	ALCANCE MAXIMO	NUM	12	2	m
ARMAS_NAVALES	CALIBRE_ARMAS	CALIBRE de ARMAS	NUM	8	2	mm
ARMAS_NAVALES	CAP_CARTUCHOS_MAGAZIN	CAPACIDAD DE CARTUCHOS MAGAZIN	NUM	9	0	      
ARMAS_NAVALES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
ARMAS_NAVALES	NUMERO_DE_ESTRIAS	NUMERO DE ESTRIAS	NUM	2	0	      
ARMAS_NAVALES	RATA_DE_FUEGO	RATA DE FUEGO EN Proyectil/min	CHAR	25	0	      
ARMAS_NAVALES	TIPO_DE_ARMA	TIPO DE ARMA	CHAR	20	0	      
ARMAS_NAVALES	TIPO_MISIL	TIPO_MISIL	CHAR	25	0	      
ARMAS_NAVALES	VELOCIDAD_MAXIMA	VELOCIDAD_MAXIMA	NUM	6	2	m/s
ARMAS_NAVALES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
BATERIAS	AMPERAJE	AMPERAJE	NUM	6	2	A
BATERIAS	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
BATERIAS	NUMERO_DE_CELDAS	NUMERO DE ELDAS	NUM	3	0	      
BATERIAS	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
BATERIAS	TIEMPO_PROMEDIO_CARGA	TIEMPO PROMEDIO CARGA	NUM	4	0	h
BATERIAS	TIPO_BATERIA	TIPO BATERIA	CHAR	20	0	      
BATERIAS	VOLTAJE_DC	VOLTAJE DC	NUM	4	0	V
BATERIAS	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
BOTES	AUTONOMIA_1	AUTONOMIA BOTES	CHAR	30	0	      
BOTES	AUTONOMIA	AUTONOMIA	NUM	12	0	Días
BOTES	ESLORA	ESLORA	NUM	5	2	m
BOTES	MANGA	MANGA	NUM	4	2	m
BOTES	CAPACIDAD_COMBUSTIBLE	CAPACIDAD DE COMBUSTIBLE	NUM	9	2	l
BOTES	DESPLAZAMIENTO	DESPLAZAMIENTO	NUM	8	3	ton
BOTES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
BOTES	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
BOTES	TIPO_BOTE	TIPO_BOTE	CHAR	25	0	      
BOTES	NUMERO_CASCO_ARC	NUMERO CASCO JEMAN	CHAR	10	0	      
BOTES	SIGLA	SIGLA INTERNACIONAL UNIDAD	CHAR	4	0	      
BOTES	FUERZA	FUERZA	CHAR	9	0	      
BOTES	FECHA_RESOLUCION_ALTA	Fecha  Resolucion Alta	DATE	10	0	      
BOTES	FECHA_RESOLUCION_BAJA	Fecha Resolucion Baja	DATE	10	0	      
BOTES	FECHA_RESOLUCION_TRASLADO	Fecha  Resolucion Traslado	DATE	10	0	      
BOTES	ACEITE_TIPO_1	TIPO DE ACEITE 1	CHAR	20	0	      
BOTES	ACEITE_TIPO_2	TIPO DE ACEITE 2	CHAR	20	0	      
BOTES	ACEITE_TIPO_3	TIPO DE ACEITE 3	CHAR	20	0	      
BOTES	ACEITE_TIPO_4	TIPO DE ACEITE 4	CHAR	20	0	      
BOTES	ULTIMA_BAJADA_DIQUE	ULTIMA BAJADA DIQUE	DATE	10	0	      
BOTES	ULTIMA_SUBIDA_DIQUE	ULTIMA SUBIDA DIQUE	DATE	10	0	      
BOTES	SITUACION_PROYECTADA_A_1_MES	SITUACION PROYECTADA A 1 MES	CHAR	3	0	      
BOTES	GRASA_TIPO_1	TIPO DE GRASA 1	CHAR	20	0	      
BOTES	GRASA_TIPO_2	TIPO DE GRASA 2	CHAR	20	0	      
BOTES	TIPO_COMBUSTIBLE_1	TIPO DE COMBUSTIBLE	CHAR	15	0	      
BOTES	PLANO_NUMERO	Plano Numero	CHAR	30	0	      
BOTES_BALSAS_SALVA	CAPACIDAD_CARGA	CAPACIDAD DE CARGA	NUM	9	2	kg
BOTES_BALSAS_SALVA	ESLORA	ESLORA	NUM	5	2	m
BOTES_BALSAS_SALVA	MANGA	MANGA	NUM	4	2	m
BOTES_BALSAS_SALVA	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
BOTES_BALSAS_SALVA	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
BOTES_BALSAS_SALVA	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
BOTES_BALSAS_SALVA	CAPACIDAD_PERSONAS	CAPACIDAD DE PERSONAS	NUM	5	0	UN
BOTES_BALSAS_SALVA	AUTONOMIA	AUTONOMIA	NUM	12	0	Días
BUQUES	TIPO_DE_ADQUISICION	TIPO DE ADQUISICION	CHAR	30	0	      
BUQUES	FECHA_DE_INCORPORACION	FECHA DE INCORPORACION	DATE	10	0	      
BUQUES	RESPONSABLE	Responsable	CHAR	30	0	      
BUQUES	SISTEMAS_DE_PUNTERIA	Sistema de Punteria	CHAR	30	0	      
BUQUES	ARMAMENTO_PRIMCIPAL	Armamento Primcipal	CHAR	30	0	      
BUQUES	ARMAMENTO_SECUNDARIO	Armamento Secundario	CHAR	30	0	      
BUQUES	ARMAMENTO_COAXIAL	Armamento Coaxial	CHAR	30	0	      
BUQUES	AUTONOMIA	AUTONOMIA	NUM	12	0	Días
BUQUES	ESLORA	ESLORA	NUM	5	2	m
BUQUES	MANGA	MANGA	NUM	4	2	m
BUQUES	CAPACIDAD_AGUA	CAPACIDAD_AGUA	NUM	8	2	l
BUQUES	CAPACIDAD_COMBUSTIBLE	CAPACIDAD DE COMBUSTIBLE	NUM	9	2	l
BUQUES	CAPACIDAD_LUBRICANTE	CAPACIDAD DE LUBRICANTE	NUM	7	2	l
BUQUES	DESPLAZAMIENTO	DESPLAZAMIENTO	NUM	8	3	ton
BUQUES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
BUQUES	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
BUQUES	LUGAR_CONSTRUCCION	LUGAR DE CONSTRUCCION	CHAR	30	0	      
BUQUES	FECHA_CONSTRUCCION	FECHA DE CONSTRUCCION	DATE	10	0	      
BUQUES	NUMERO_CASCO_ARC	NUMERO CASCO JEMAN	CHAR	10	0	      
BUQUES	TIPO_PROPULSION	TIPO DE PROPULSION	CHAR	30	0	      
BUQUES	PUNTAL	PUNTAL	NUM	4	2	m
BUQUES	TIPO_BUQUE	TIPO DE BUQUE	CHAR	28	0	      
BUQUES	CALADO	CALADO	NUM	9	2	Pie
BUQUES	SIGLA	SIGLA INTERNACIONAL UNIDAD	CHAR	4	0	      
BUQUES	FUERZA	FUERZA	CHAR	9	0	      
BUQUES	FECHA_RESOLUCION_ALTA	Fecha  Resolucion Alta	DATE	10	0	      
BUQUES	FECHA_RESOLUCION_BAJA	Fecha Resolucion Baja	DATE	10	0	      
BUQUES	FECHA_RESOLUCION_TRASLADO	Fecha  Resolucion Traslado	DATE	10	0	      
BUQUES	ULTIMA_SUBIDA_DIQUE	ULTIMA SUBIDA DIQUE	DATE	10	0	      
BUQUES	ULTIMA_BAJADA_DIQUE	ULTIMA BAJADA DIQUE	DATE	10	0	      
BUQUES	ACEITE_TIPO_1	TIPO DE ACEITE 1	CHAR	20	0	      
BUQUES	ACEITE_TIPO_2	TIPO DE ACEITE 2	CHAR	20	0	      
BUQUES	ACEITE_TIPO_3	TIPO DE ACEITE 3	CHAR	20	0	      
BUQUES	ACEITE_TIPO_4	TIPO DE ACEITE 4	CHAR	20	0	      
BUQUES	GRASA_TIPO_1	TIPO DE GRASA 1	CHAR	20	0	      
BUQUES	GRASA_TIPO_2	TIPO DE GRASA 2	CHAR	20	0	      
BUQUES	TIPO_COMBUSTIBLE_1	TIPO DE COMBUSTIBLE	CHAR	15	0	      
BUQUES	SITUACION_PROYECTADA_A_1_MES	SITUACION PROYECTADA A 1 MES	CHAR	3	0	      
BUQUES	PLANO_NUMERO	Plano Numero	CHAR	30	0	      
CABRES_WINCHE_GRUA	TIPO_ANCLA	TIPO_ANCLA	CHAR	20	0	      
CABRES_WINCHE_GRUA	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
CABRES_WINCHE_GRUA	TAMANO_ANCLA	TAMANO ANCLA	NUM	4	0	      
CABRES_WINCHE_GRUA	TAMANO_ESLABONES	TAMANO ESLABONES	NUM	6	2	      
CABRES_WINCHE_GRUA	LONGITUD_DE_CADENA	LONGITUD DE CADENA	NUM	5	2	m
CABRES_WINCHE_GRUA	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
CABRES_WINCHE_GRUA	TIPO_ACCIONAMIENTO	TIPO DE ACCIONAMIENTO	CHAR	30	0	      
CABRES_WINCHE_GRUA	CAPACIDAD_LEVANTE	CAPACIDAD LEVANTE	NUM	8	0	      
CABRES_WINCHE_GRUA	DIAMETRO_MINIMO_TAMBOR	DIAMETRO MINIMO TAMBOR	NUM	5	2	mm
CABRES_WINCHE_GRUA	DIAMETRO_MAXIMO_TAMBOR	DIAMETRO MAXIMO TAMBOR	NUM	5	2	mm
CABRES_WINCHE_GRUA	TIPO_FRENO	Tipo de freno	CHAR	20	0	      
CASCO_CUBIERTA	ESPESOR_MATERIAL	ESPESOR  MATERIAL	NUM	5	0	      
CASCO_CUBIERTA	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
CASCO_CUBIERTA	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
CASCO_CUBIERTA	NORMA	 NORMA	CHAR	25	0	      
CASCO_CUBIERTA	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
CASCO_CUBIERTA	NUMERO_CASCO_ARC	NUMERO CASCO JEMAN	CHAR	10	0	      
COJINETES_EJES	CAPACIDAD_LITROS	CAPACIDAD EN LITROS	NUM	8	2	l
COJINETES_EJES	LONGITUD_TOTAL	LONGITUD TOTAL	NUM	8	2	mm
COJINETES_EJES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
COJINETES_EJES	RATA_DE_EMPUJE_KGCM2	RATA DE EMPUJE Kg/cm2	NUM	6	2	      
COJINETES_EJES	RPM	RPM	NUM	9	2	rpm
COJINETES_EJES	RPM_DE_DISENO	RPM DE DISENO	NUM	7	0	rpm
COJINETES_EJES	SHP_DE_DISENO	SHP DE DISENO	NUM	7	2	      
COJINETES_EJES	SUPERFICIE_EMPUJE	SUPERFICIE EMPUJE	NUM	6	0	      
COJINETES_EJES	SUPERFICIE_FRICCION	SUPERFICIE FRICCION	CHAR	20	0	      
COJINETES_EJES	TIPO_COJINETES_EJES	TIPO COJINETES EJES	CHAR	20	0	      
COJINETES_EJES	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
COJINETES_EJES	TOLERANCIA	TOLERANCIA	CHAR	20	0	      
COJINETES_EJES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
COJINETES_EJES	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
COJINETES_EJES	DIAMETRO_EJE	DIAMETRO EJE	NUM	6	2	mm
COJINETES_EJES	ESFUERZO_TORQUE_NOMINAL	ESFUERZO TORQUE NOMINAL	NUM	6	2	
COJINETES_EJES	NUMERO_DE_SECCIONES	NUMERO DE SECCIONES	NUM	3	0	
COJINETES_EJES	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	
COJINETES_EJES	NUMERO_COJINETES_DE_EMPUJE	NUMERO COJINETES DE EMPUJE	NUM	3	0	
COJINETES_EJES	NUMERO_COJINETES_DE_SOPORTE	NUMERO COJINETES DE SOPORTE	NUM	2	0	
COMPRESORES	TIPO_COMPRESOR	TIPO COMPRESOR	CHAR	20	0	      
COMPRESORES	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
COMPRESORES	TIPO_REFRIGERANTE	TIPO REFRIGERANTE	CHAR	20	0	      
COMPRESORES	VOLTAJE	Voltaje	NUM	6	2	V
COMPRESORES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
COMPRESORES	AMPERAJE	AMPERAJE	NUM	6	2	A
COND_EVAP_INTERCAM	PRESION_DESCARGA_BAR	PRESION DESCARGA BAR	NUM	6	2	bar
COND_EVAP_INTERCAM	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
COND_EVAP_INTERCAM	TIPO_REFRIGERANTE	TIPO REFRIGERANTE	CHAR	20	0	      
COND_EVAP_INTERCAM	PRESION_SUCCION	PRESION SUCCION	NUM	6	2	bar
ENG_REDUCTORES	CAPACIDAD_LUBRICANTE	CAPACIDAD DE LUBRICANTE	NUM	7	2	l
ENG_REDUCTORES	EMPUJE_DE_LA_HELICE	EMPUJE DE LA HELICE	NUM	6	2	kN
ENG_REDUCTORES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
ENG_REDUCTORES	POTENCIA_NOMINAL_HP	POTENCIA NOMINAL HP	NUM	7	2	      
ENG_REDUCTORES	PRESION	PRESION	NUM	6	2	bar
ENG_REDUCTORES	RPM	RPM	NUM	9	2	rpm
ENG_REDUCTORES	TIPO_ENGRANAJES	TIPO ENGRANAJES	CHAR	20	0	      
ENG_REDUCTORES	VELOCIDAD_NOMINAL_ENTRADA_N1	VELOCIDAD_NOMINAL_ENTRADA_N1	NUM	7	2	rpm
ENG_REDUCTORES	VELOCIDAD_NOMINAL_SALIDA_N2	VELOCIDAD NOMINAL SALIDA N2	NUM	7	2	rpm
ENG_REDUCTORES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
EQ_ELECT_RADAR_COM	AMPERAJE_PRIMARIO	AMPERAJE PRIMARIO	NUM	6	2	A
EQ_ELECT_RADAR_COM	AMPERAJE_SECUNDARIO	AMPERAJE SECUNDARIO	NUM	6	2	A
EQ_ELECT_RADAR_COM	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
EQ_ELECT_RADAR_COM	ESTABILIZACION_EN_ROLIDO	ESTABILIZACION EN ROLIDO	CHAR	20	0	      
EQ_ELECT_RADAR_COM	ESPACIAMIENTO_CANAL	Espaciamiento Canal	CHAR	30	0	      
EQ_ELECT_RADAR_COM	ELEVACION_COVERTURA	Covertura de Elevacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	FRECUENCIA_TRANSMISION	FRECUENCIA TRANSMISION	CHAR	20	0	      
EQ_ELECT_RADAR_COM	FASE	Fase	CHAR	30	0	      
EQ_ELECT_RADAR_COM	FRECUENCIA_OPERACION	Frecuencia Operacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
EQ_ELECT_RADAR_COM	IMPEDANCIA_ANTENA	Impedancia antena	CHAR	30	0	      
EQ_ELECT_RADAR_COM	INTERMODULACION	Intermodulacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
EQ_ELECT_RADAR_COM	MODULACION	Modulacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	POTENCIA_DE_TRANSMISION	POTENCIA DE TRANSMISION	NUM	4	2	      
EQ_ELECT_RADAR_COM	POTENCIA_DEL_MAGNETRON	POTENCIA DEL MAGNETRON	NUM	5	2	      
EQ_ELECT_RADAR_COM	POTENCIA_DISIPADA	POTENCIA DISIPADA	NUM	6	2	W
EQ_ELECT_RADAR_COM	PRF_CORTO	PRF CORTO	NUM	4	2	      
EQ_ELECT_RADAR_COM	PRF_LARGO	PRF LARGO	NUM	4	2	      
EQ_ELECT_RADAR_COM	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
EQ_ELECT_RADAR_COM	POTENCIA_SALIDA	Potencia de Salida	CHAR	30	0	      
EQ_ELECT_RADAR_COM	PULSO	Pulso	CHAR	30	0	      
EQ_ELECT_RADAR_COM	PRF	Prf	CHAR	30	0	      
EQ_ELECT_RADAR_COM	POLARIZACION	Polarizacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	RED	Red de Operacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	RPMS	RPMS	CHAR	30	0	      
EQ_ELECT_RADAR_COM	RESPONSABLE	Responsable	CHAR	30	0	      
EQ_ELECT_RADAR_COM	RATA_ROTACION	Rata de Rotacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	RANGO_FRECUENCIA	Rango Frecuencia	CHAR	30	0	      
EQ_ELECT_RADAR_COM	SENSIBILIDAD	Sensibilidad	CHAR	30	0	      
EQ_ELECT_RADAR_COM	SECTOR_BLANKING	Sector Blanking	CHAR	30	0	      
EQ_ELECT_RADAR_COM	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
EQ_ELECT_RADAR_COM	TIPO_DE_ANTENA	TIPO DE ANTENA	CHAR	20	0	      
EQ_ELECT_RADAR_COM	TIPO_RADAR	TIPO RADAR	CHAR	20	0	      
EQ_ELECT_RADAR_COM	TIPO_DE_EQUIPO	TIPO DE EQUIPO	CHAR	20	0	      
EQ_ELECT_RADAR_COM	USO	Uso	CHAR	30	0	      
EQ_ELECT_RADAR_COM	VOLTAGE_ALIMENTACION	Voltage Alimentacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	VELOCIDAD_ROTACION_ANTENA	VELOCIDAD ROTACION ANTENA	NUM	5	2	rpm
EQ_ELECT_RADAR_COM	ANTENA_PARADA	ANTENA PARADA	CHAR	20	0	      
EQ_ELECT_RADAR_COM	ANTENA_ROTACION	ANTENA DE ROTACION	CHAR	20	0	      
EQ_ELECT_RADAR_COM	ALGORITMO_ENCRIPCION	ALGORITMO_ENCRIPCION	CHAR	30	0	      
EQ_ELECT_RADAR_COM	CONSUMO_POTENCIA	Consumo Potencia	CHAR	30	0	      
EQ_ELECT_RADAR_COM	ESPECIALIDAD	Especialidad	CHAR	30	0	      
EQ_ELECT_RADAR_COM	AMPERAJE	AMPERAJE	NUM	6	2	A
EQ_ELECT_RADAR_COM	ALCANCE_MAXIMO	ALCANCE MAXIMO	NUM	12	2	m
EQ_ELECT_RADAR_COM	ANCHO_DE_PULSO	ANCHO_DE_PULSO	NUM	10	2	mm
EQ_ELECT_RADAR_COM	AZIMUTH	Azimuth	CHAR	30	0	      
EQ_ELECT_RADAR_COM	ELE_VACION	Elevacion	CHAR	30	0	      
EQ_ELECT_RADAR_COM	LONGITUD_DE_RADIADOR	LONGITUD DE RADIADOR	NUM	4	2	m
EQ_ELECT_RADAR_COM	VOLTAJE	Voltaje	NUM	6	2	V
EQ_ELECT_RADAR_COM	VOLTAJE_DC	VOLTAJE DC	NUM	4	0	V
EQ_ELECT_RADAR_COM	NO_CANALES	NUMERO DE CANALES	NUM	15	0	UN
EQ_ELECT_RADAR_COM	CLAVES	CLAVES O LLAVES	NUM	4	0	UN
EQ_ELECT_RADAR_COM	MODO_OPERACION	MODO DE OPERACION	CHAR	30	0	      
EQ_ELECT_RADAR_COM	CANALES	CANALES	NUM	10	0	UN
EQ_ELECT_RADAR_COM	BANDA	BANDA DE OPERACION	CHAR	3	0	      
EQ_ELECT_RADAR_COM	DESVIACION	DESVIACION DE FRECUENCIA	CHAR	30	0	      
EQ_ELECT_RADAR_COM	UNIDAD_DE_ASIGNACIOM	UNIDAD DE ASIGNACION	CHAR	30	0	      
EQ_ELECTRIC_TALLER	DIAMETRO_EJE	DIAMETRO EJE	NUM	6	2	mm
EQ_ELECTRIC_TALLER	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
EQ_ELECTRIC_TALLER	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
EQ_ELECTRIC_TALLER	CLASE_PROTECCION	CLASE DE PROTECCION	CHAR	25	0	      
EQ_ELECTRIC_TALLER	REF_RODAMIENTO	REFERENCIA DE RODAMIENTO	CHAR	25	0	      
EQ_ELECTRIC_TALLER	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
EQ_ELECTRIC_TALLER	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
EQ_ELECTRIC_TALLER	AMPERAJE	AMPERAJE	NUM	6	2	A
EQ_ELECTRIC_TALLER	VOLTAJE	Voltaje	NUM	6	2	V
EQ_ELECTRIC_TALLER	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
EQ_ELECTRIC_TALLER	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
EQ_ELECTRIC_TALLER	RPM	RPM	NUM	9	2	rpm
EQ_ELECTRIC_TALLER	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
EQ_ELECTRIC_TALLER	TIPO_DE_EQUIPO	TIPO DE EQUIPO	CHAR	20	0	      
EQ_ELECTRIC_TALLER	POTENCIA_HP	POTENCIA HP	NUM	6	2	      
EQ_ELECTRIC_TALLER	POTENCIA_HP	POTENCIA HP	NUM	6	2	      
EQ_REFRIGER	CAPACIDAD_BTUH	CAPACIDAD_BTUH	NUM	9	0	      
EQ_REFRIGER	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
EQ_REFRIGER	NUMERO_DE_CILINDROS	NUMERO_DE_CILINDROS	NUM	2	0	      
EQ_REFRIGER	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
EQ_REFRIGER	RPM	RPM	NUM	9	2	rpm
EQ_REFRIGER	TIPO_COMPRESOR	TIPO COMPRESOR	CHAR	20	0	      
EQ_REFRIGER	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
EQ_REFRIGER	TIPO_REFRIGERANTE	TIPO REFRIGERANTE	CHAR	20	0	      
EQ_REFRIGER	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
EQ_REFRIGER	AMPERAJE	AMPERAJE	NUM	6	2	A
EQ_REFRIGER	VOLTAJE	Voltaje	NUM	6	2	V
EQ_REFRIGER	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
EQ_RESP_BOT_EXTINT	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
EQ_RESP_BOT_EXTINT	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
EQ_RESP_BOT_EXTINT	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
EQ_RESP_BOT_EXTINT	PRESION_MAX	PRESION MAXIMA DE TRABAJO	CHAR	10	0	      
EQ_RESP_BOT_EXTINT	AGENTE_EXTINTOR_ABC	AGENTE EXTINTOR ABC	CHAR	12	0	      
EQ_RESP_BOT_EXTINT	CAPACIDAD_LIBRAS	CAPACIDAD EN LIBRAS	NUM	7	0	      
EQ_RESP_BOT_EXTINT	CAPACIDAD_LITROS	CAPACIDAD EN LITROS	NUM	8	2	l
EQ_RESP_BOT_EXTINT	CAUDAL_LPM	CAUDAL EN l/min	NUM	6	2	      
EQ_RESP_BOT_EXTINT	GAS_PROPULSION	GAS PROPULSION	CHAR	20	0	      
EQ_RESP_BOT_EXTINT	LONG_DE_DISPARO	LONGITUD DE DISPARO	NUM	5	0	m
EQ_RESP_BOT_EXTINT	PRESION_DE_PRUEBA_BAR	PRESION DE PRUEBA_BAR	NUM	6	2	bar
EQ_RESP_BOT_EXTINT	PRESION_DESCARGA_BAR	PRESION DESCARGA BAR	NUM	6	2	bar
EQ_RESP_BOT_EXTINT	PRESION_DESCARGA_PSI	PRESION DESCARGA PSI	NUM	6	2	psi
EQ_RESP_BOT_EXTINT	TIPO_EXTINTOR	TIPO EXTINTOR	CHAR	15	0	      
EQ_RESP_BOT_EXTINT	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
EQ_RESP_BOT_EXTINT	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
GENERADORES	AMPERAJE	AMPERAJE	NUM	6	2	A
GENERADORES	CLASE_AISLAMIENTO	CLASE DE AISLAMIENTO	CHAR	8	0	      
GENERADORES	CLASE_PROTECCION	CLASE DE PROTECCION	CHAR	25	0	      
GENERADORES	FACTOR_DE_POTENCIA	FACTOR DE POTENCIA	NUM	4	2	%
GENERADORES	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
GENERADORES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
GENERADORES	POTENCIA_HP	POTENCIA HP	NUM	6	2	      
GENERADORES	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
GENERADORES	REF_RODAMIENTO	REFERENCIA DE RODAMIENTO	CHAR	25	0	      
GENERADORES	RPM	RPM	NUM	9	2	rpm
GENERADORES	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
GENERADORES	TEMPERATURA_AMBIENTE	TEMPERATURA AMBIENTE	NUM	5	2	°C
GENERADORES	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
GENERADORES	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	      
GENERADORES	TIPO_AMORTIGUACION	TIPO AMORTIGUACION	CHAR	20	0	      
GENERADORES	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
GENERADORES	VOLTAJE	Voltaje	NUM	6	2	V
GENERADORES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
GRUP_VENT_BLOWER	CAUDAL_M3H	CAUDAL EN m3/h	NUM	6	2	m3/h
GRUP_VENT_BLOWER	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
GRUP_VENT_BLOWER	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
GRUP_VENT_BLOWER	RPM	RPM	NUM	9	2	rpm
GRUP_VENT_BLOWER	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
GRUP_VENT_BLOWER	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
GRUP_VENT_BLOWER	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
HELICES	DIAMETRO_HELICE	DIAMETRO HELICE	NUM	7	2	mm
HELICES	DIAMETRO_NUCLEO	DIAMETRO NUCLEO	NUM	5	2	mm
HELICES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
HELICES	NUMERO_DE_PALAS	NUMERO DE PALAS	NUM	2	0	      
HELICES	RPM	RPM	NUM	9	2	rpm
HELICES	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
HELICES	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	      
HELICES	TIPO_HELICE	TIPO HELICE	CHAR	20	0	      
HELICES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
HELICES	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
MOTORES_DIESEL	CAPACIDAD_LUBRICANTE	CAPACIDAD DE LUBRICANTE	NUM	7	2	l
MOTORES_DIESEL	CARRERA_DEL_PISTON	CARRERA DEL PISTON	NUM	5	2	mm
MOTORES_DIESEL	CICLO_TRABAJO	CICLO DE TRABAJO	CHAR	10	0	      
MOTORES_DIESEL	DIAMETRO_CILINDRO	DIAMETRO CILINDRO	NUM	6	2	mm
MOTORES_DIESEL	FECHA_ULTIMO_MANTTO	FECHA ULTIMO MANTTO	DATE	10	0	      
MOTORES_DIESEL	INYECCION	INYECCION	CHAR	20	0	      
MOTORES_DIESEL	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
MOTORES_DIESEL	NUMERO_DE_CILINDROS	NUMERO_DE_CILINDROS	NUM	2	0	      
MOTORES_DIESEL	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
MOTORES_DIESEL	PRESION_DE_AIRE_ARRANQUE	PRESION DE AIRE ARRANQUE	NUM	6	2	psi
MOTORES_DIESEL	RELACION_DE_COMPRESION	RELACION DE COMPRESION	CHAR	20	0	      
MOTORES_DIESEL	RPM	RPM	NUM	9	2	rpm
MOTORES_DIESEL	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
MOTORES_DIESEL	SISTEMA_ARRANQUE	SISTEMA ARRANQUE	CHAR	25	0	      
MOTORES_DIESEL	SISTEMA_ENFRIAMIENTO	SISTEMA ENFRIAMIENTO	CHAR	25	0	      
MOTORES_DIESEL	TIPO_ACEITE	TIPO_ACEITE	CHAR	20	0	      
MOTORES_DIESEL	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	      
MOTORES_DIESEL	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
MOTORES_DIESEL	TIPO_MOTOR	TIPO MOTOR	CHAR	20	0	      
MOTORES_DIESEL	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
MOTORES_DIESEL	POTENCIA_HP	POTENCIA HP	NUM	6	2	      
MOTORES_DIESEL	PLANO_NUMERO	Plano Numero	CHAR	30	0	      
MOTORES_ELECTRICOS	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
MOTORES_ELECTRICOS	TEMPERATURA_AMBIENTE	TEMPERATURA AMBIENTE	NUM	5	2	°C
MOTORES_ELECTRICOS	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
MOTORES_ELECTRICOS	TIPO_ACOPLE	TIPO ACOPLE	CHAR	20	0	      
MOTORES_ELECTRICOS	TIPO_CORRIENTE	Tipo de corriente	CHAR	10	0	      
MOTORES_ELECTRICOS	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
MOTORES_ELECTRICOS	VOLTAJE	Voltaje	NUM	6	2	V
MOTORES_ELECTRICOS	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
MOTORES_FUERA_BOR	RPM	RPM	NUM	9	2	rpm
MOTORES_FUERA_BOR	SENTIDO_GIRO	SENTIDO GIRO	CHAR	20	0	      
MOTORES_FUERA_BOR	SISTEMA_ARRANQUE	SISTEMA ARRANQUE	CHAR	25	0	      
MOTORES_FUERA_BOR	SISTEMA_DE_INCLINACION	SISTEMA DE INCLINACION	CHAR	20	0	      
MOTORES_FUERA_BOR	SISTEMA_LUBRICACION	SISTEMA LUBRICACION	CHAR	20	0	      
MOTORES_FUERA_BOR	TIPO_ACEITE	TIPO_ACEITE	CHAR	20	0	      
MOTORES_FUERA_BOR	TIPO_MOTOR	TIPO MOTOR	CHAR	20	0	      
MOTORES_FUERA_BOR	FAMILIA	FAMILIA MOTOR F/B	NUM	3	0	      
MOTORES_FUERA_BOR	ESTADO_RODAJE_INICIAL	EST. RODAJE INICIAL MOTOR F/B	CHAR	15	0	      
MOTORES_FUERA_BOR	USUARIO_GEN_REPORTE	USUARIO GENERADOR REPORTE	CHAR	20	0	      
MOTORES_FUERA_BOR	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
MOTORES_FUERA_BOR	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
MOTORES_FUERA_BOR	PLANO_NUMERO	Plano Numero	CHAR	30	0	      
PLANTA_TRATAMIENTO	CAUDAL_M3H	CAUDAL EN m3/h	NUM	6	2	m3/h
PLANTA_TRATAMIENTO	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
PLANTA_TRATAMIENTO	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
PLANTA_TRATAMIENTO	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
PLANTA_TRATAMIENTO	VOLTAJE	Voltaje	NUM	6	2	V
PLANTA_TRATAMIENTO	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
PLANTA_TRATAMIENTO	AMPERAJE	AMPERAJE	NUM	6	2	A
PURIFICADORES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
PURIFICADORES	PRESION_DESCARGA_BAR	PRESION DESCARGA BAR	NUM	6	2	bar
PURIFICADORES	PRESION_SUCCION	PRESION SUCCION	NUM	6	2	bar
PURIFICADORES	RPM	RPM	NUM	9	2	rpm
PURIFICADORES	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
PURIFICADORES	TIPO_PURIFICADORES	TIPO PURIFICADORES	CHAR	20	0	      
PURIFICADORES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
PURIFICADORES	CAUDAL_M3H	CAUDAL EN m3/h	NUM	6	2	m3/h
PURIFICADORES	TIPO_DE_FLUIDO	TIPO DE FLUIDO	CHAR	20	0	      
TABLERO_ELECTRICO	AMPERAJE	AMPERAJE	NUM	6	2	A
TABLERO_ELECTRICO	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
TABLERO_ELECTRICO	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
TABLERO_ELECTRICO	TEMPERATURA_TRABAJO	TEMPERATURA TRABAJO	NUM	5	2	°C
TABLERO_ELECTRICO	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
TABLERO_ELECTRICO	VOLTAJE	Voltaje	NUM	6	2	V
TABLERO_ELECTRICO	VOLTAJE_DC	VOLTAJE DC	NUM	4	0	V
TABLERO_ELECTRICO	CLASE_PROTECCION	CLASE DE PROTECCION	CHAR	25	0	      
TABLERO_ELECTRICO	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
TANQUES	CAPACIDAD_LITROS	CAPACIDAD EN LITROS	NUM	8	2	l
TANQUES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
TANQUES	PRESION_DESCARGA_BAR	PRESION DESCARGA BAR	NUM	6	2	bar
TANQUES	TIPO_MONTAJE	TIPO MONTAJE	CHAR	20	0	      
TANQUES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
TANQUES	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
TANQUES	TIPO_DE_FLUIDO	TIPO DE FLUIDO	CHAR	20	0	      
TRANSFORMADORES	AMPERAJE_PRIMARIO	AMPERAJE PRIMARIO	NUM	6	2	A
TRANSFORMADORES	AMPERAJE_SECUNDARIO	AMPERAJE SECUNDARIO	NUM	6	2	A
TRANSFORMADORES	CALIBRE_ALAMBRE	CALIBRE ALAMBRE	CHAR	5	0	      
TRANSFORMADORES	CLASE_AISLAMIENTO	CLASE DE AISLAMIENTO	CHAR	8	0	      
TRANSFORMADORES	CLASE_PROTECCION	CLASE DE PROTECCION	CHAR	25	0	      
TRANSFORMADORES	FRECUENCIA	FRECUENCIA	NUM	5	2	hz
TRANSFORMADORES	FUSIBLE_DE_PROTECCION	FUSIBLE DE PROTECCION	CHAR	25	0	      
TRANSFORMADORES	MANUALES_TECNICOS	MANUALES TECNICOS	CHAR	30	0	      
TRANSFORMADORES	NUMERO_ESPIRAS_PRIMARIO	NUMERO ESPIRAS PRIMARIO	NUM	3	0	      
TRANSFORMADORES	POTENCIA_KW	POTENCIA EN Kw	NUM	7	2	kw
TRANSFORMADORES	PROTECCION_ANTICHOQUE	PROTECCION ANTICHOQUE	CHAR	25	0	      
TRANSFORMADORES	TIPO_DE_CONEXION	TIPO DE CONEXION	CHAR	20	0	      
TRANSFORMADORES	TOLERANCIA_EN_PORCENTAJE	TOLERANCIA EN PORCENTAJE	NUM	5	2	%
TRANSFORMADORES	VOLTAJE_PRIMARIO	VOLTAJE PRIMARIO	NUM	4	0	      
TRANSFORMADORES	VOLTAJE_SECUNDARIO	VOLTAJE SECUNDARIO	NUM	4	0	V
TRANSFORMADORES	VOLTAJE	Voltaje	NUM	6	2	V
TRANSFORMADORES	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
VALVULAS	VOLTAJE_DC	VOLTAJE DC	NUM	4	0	V
VALVULAS	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
VALVULAS	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
VALVULAS	PRESION_SUCCION	PRESION SUCCION	NUM	6	2	bar
VENTILAD_EXTRACTOR	VOLTAJE	Voltaje	NUM	6	2	V
VENTILAD_EXTRACTOR	CONTROL_VIDA_UTIL	CONTROL VIDA UTIL	CHAR	28	0	      
VENTILAD_EXTRACTOR	TIPO_MATERIAL	TIPO MATERIAL	CHAR	20	0	      
"""

generar_sql(descripcion)




