INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'CABEZA_DE_SUCCION', 'CABEZA DE SUCCION', 'NUM', 8, 0, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'CAUDAL_LPM', 'CAUDAL EN l/min', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'DIAMETRO_DESCARGA', 'DIAMETRO DESCARGA', 'NUM', 4, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'DIAMETRO_EJE', 'DIAMETRO EJE', 'NUM', 6, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'DIAMETRO_SUCCION', 'DIAMETRO SUCCION', 'NUM', 5, 3, 'Pulg.');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'ETAPAS', 'ETAPAS', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'POTENCIA_HP', 'POTENCIA HP', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'PRESION_DE_SERVICIO', 'PRESION DE SERVICIO', 'NUM', 6, 2, 'psi');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'PRESION_DESCARGA_BAR', 'PRESION DESCARGA BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'PRESION_SUCCION', 'PRESION SUCCION', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'REF_RODAMIENTO', 'REFERENCIA DE RODAMIENTO', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_BOMBA', 'TIPO BOMBA', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_DE_IMPULSION', 'TIPO DE IMPULSION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'TIPO_SELLO', 'TIPO SELLO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOMBAS', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'ALCANCE_EFECTIVO', 'ALCANCE EFECTIVO', 'NUM', 12, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'ALCANCE_MAXIMO', 'ALCANCE MAXIMO', 'NUM', 12, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'CALIBRE_ARMAS', 'CALIBRE de ARMAS', 'NUM', 8, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'CAP_CARTUCHOS_MAGAZIN', 'CAPACIDAD DE CARTUCHOS MAGAZIN', 'NUM', 9, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'NUMERO_DE_ESTRIAS', 'NUMERO DE ESTRIAS', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'RATA_DE_FUEGO', 'RATA DE FUEGO EN Proyectil/min', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'TIPO_DE_ARMA', 'TIPO DE ARMA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'TIPO_MISIL', 'TIPO_MISIL', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'VELOCIDAD_MAXIMA', 'VELOCIDAD_MAXIMA', 'NUM', 6, 2, 'm/s');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ARMAS_NAVALES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'NUMERO_DE_CELDAS', 'NUMERO DE ELDAS', 'NUM', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'TIEMPO_PROMEDIO_CARGA', 'TIEMPO PROMEDIO CARGA', 'NUM', 4, 0, 'h');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'TIPO_BATERIA', 'TIPO BATERIA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'VOLTAJE_DC', 'VOLTAJE DC', 'NUM', 4, 0, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BATERIAS', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'AUTONOMIA_1', 'AUTONOMIA BOTES', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'AUTONOMIA', 'AUTONOMIA', 'NUM', 12, 0, 'Días');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ESLORA', 'ESLORA', 'NUM', 5, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'MANGA', 'MANGA', 'NUM', 4, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'CAPACIDAD_COMBUSTIBLE', 'CAPACIDAD DE COMBUSTIBLE', 'NUM', 9, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'DESPLAZAMIENTO', 'DESPLAZAMIENTO', 'NUM', 8, 3, 'ton');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'TIPO_BOTE', 'TIPO_BOTE', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'NUMERO_CASCO_ARC', 'NUMERO CASCO JEMAN', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'SIGLA', 'SIGLA INTERNACIONAL UNIDAD', 'CHAR', 4, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'FUERZA', 'FUERZA', 'CHAR', 9, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'FECHA_RESOLUCION_ALTA', 'Fecha  Resolucion Alta', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'FECHA_RESOLUCION_BAJA', 'Fecha Resolucion Baja', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'FECHA_RESOLUCION_TRASLADO', 'Fecha  Resolucion Traslado', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ACEITE_TIPO_1', 'TIPO DE ACEITE 1', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ACEITE_TIPO_2', 'TIPO DE ACEITE 2', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ACEITE_TIPO_3', 'TIPO DE ACEITE 3', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ACEITE_TIPO_4', 'TIPO DE ACEITE 4', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ULTIMA_BAJADA_DIQUE', 'ULTIMA BAJADA DIQUE', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'ULTIMA_SUBIDA_DIQUE', 'ULTIMA SUBIDA DIQUE', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'SITUACION_PROYECTADA_A_1_MES', 'SITUACION PROYECTADA A 1 MES', 'CHAR', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'GRASA_TIPO_1', 'TIPO DE GRASA 1', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'GRASA_TIPO_2', 'TIPO DE GRASA 2', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'TIPO_COMBUSTIBLE_1', 'TIPO DE COMBUSTIBLE', 'CHAR', 15, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES', 'PLANO_NUMERO', 'Plano Numero', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'CAPACIDAD_CARGA', 'CAPACIDAD DE CARGA', 'NUM', 9, 2, 'kg');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'ESLORA', 'ESLORA', 'NUM', 5, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'MANGA', 'MANGA', 'NUM', 4, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'CAPACIDAD_PERSONAS', 'CAPACIDAD DE PERSONAS', 'NUM', 5, 0, 'UN');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BOTES_BALSAS_SALVA', 'AUTONOMIA', 'AUTONOMIA', 'NUM', 12, 0, 'Días');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'TIPO_DE_ADQUISICION', 'TIPO DE ADQUISICION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FECHA_DE_INCORPORACION', 'FECHA DE INCORPORACION', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'RESPONSABLE', 'Responsable', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'SISTEMAS_DE_PUNTERIA', 'Sistema de Punteria', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ARMAMENTO_PRIMCIPAL', 'Armamento Primcipal', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ARMAMENTO_SECUNDARIO', 'Armamento Secundario', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ARMAMENTO_COAXIAL', 'Armamento Coaxial', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'AUTONOMIA', 'AUTONOMIA', 'NUM', 12, 0, 'Días');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ESLORA', 'ESLORA', 'NUM', 5, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'MANGA', 'MANGA', 'NUM', 4, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'CAPACIDAD_AGUA', 'CAPACIDAD_AGUA', 'NUM', 8, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'CAPACIDAD_COMBUSTIBLE', 'CAPACIDAD DE COMBUSTIBLE', 'NUM', 9, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'CAPACIDAD_LUBRICANTE', 'CAPACIDAD DE LUBRICANTE', 'NUM', 7, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'DESPLAZAMIENTO', 'DESPLAZAMIENTO', 'NUM', 8, 3, 'ton');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'LUGAR_CONSTRUCCION', 'LUGAR DE CONSTRUCCION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FECHA_CONSTRUCCION', 'FECHA DE CONSTRUCCION', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'NUMERO_CASCO_ARC', 'NUMERO CASCO JEMAN', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'TIPO_PROPULSION', 'TIPO DE PROPULSION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'PUNTAL', 'PUNTAL', 'NUM', 4, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'TIPO_BUQUE', 'TIPO DE BUQUE', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'CALADO', 'CALADO', 'NUM', 9, 2, 'Pie');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'SIGLA', 'SIGLA INTERNACIONAL UNIDAD', 'CHAR', 4, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FUERZA', 'FUERZA', 'CHAR', 9, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FECHA_RESOLUCION_ALTA', 'Fecha  Resolucion Alta', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FECHA_RESOLUCION_BAJA', 'Fecha Resolucion Baja', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'FECHA_RESOLUCION_TRASLADO', 'Fecha  Resolucion Traslado', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ULTIMA_SUBIDA_DIQUE', 'ULTIMA SUBIDA DIQUE', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ULTIMA_BAJADA_DIQUE', 'ULTIMA BAJADA DIQUE', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ACEITE_TIPO_1', 'TIPO DE ACEITE 1', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ACEITE_TIPO_2', 'TIPO DE ACEITE 2', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ACEITE_TIPO_3', 'TIPO DE ACEITE 3', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'ACEITE_TIPO_4', 'TIPO DE ACEITE 4', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'GRASA_TIPO_1', 'TIPO DE GRASA 1', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'GRASA_TIPO_2', 'TIPO DE GRASA 2', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'TIPO_COMBUSTIBLE_1', 'TIPO DE COMBUSTIBLE', 'CHAR', 15, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'SITUACION_PROYECTADA_A_1_MES', 'SITUACION PROYECTADA A 1 MES', 'CHAR', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('BUQUES', 'PLANO_NUMERO', 'Plano Numero', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'TIPO_ANCLA', 'TIPO_ANCLA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'TAMANO_ANCLA', 'TAMANO ANCLA', 'NUM', 4, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'TAMANO_ESLABONES', 'TAMANO ESLABONES', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'LONGITUD_DE_CADENA', 'LONGITUD DE CADENA', 'NUM', 5, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'TIPO_ACCIONAMIENTO', 'TIPO DE ACCIONAMIENTO', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'CAPACIDAD_LEVANTE', 'CAPACIDAD LEVANTE', 'NUM', 8, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'DIAMETRO_MINIMO_TAMBOR', 'DIAMETRO MINIMO TAMBOR', 'NUM', 5, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'DIAMETRO_MAXIMO_TAMBOR', 'DIAMETRO MAXIMO TAMBOR', 'NUM', 5, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CABRES_WINCHE_GRUA', 'TIPO_FRENO', 'Tipo de freno', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'ESPESOR_MATERIAL', 'ESPESOR  MATERIAL', 'NUM', 5, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'NORMA', 'NORMA', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('CASCO_CUBIERTA', 'NUMERO_CASCO_ARC', 'NUMERO CASCO JEMAN', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'CAPACIDAD_LITROS', 'CAPACIDAD EN LITROS', 'NUM', 8, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'LONGITUD_TOTAL', 'LONGITUD TOTAL', 'NUM', 8, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'RATA_DE_EMPUJE_KGCM2', 'RATA DE EMPUJE Kg/cm2', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'RPM_DE_DISENO', 'RPM DE DISENO', 'NUM', 7, 0, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'SHP_DE_DISENO', 'SHP DE DISENO', 'NUM', 7, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'SUPERFICIE_EMPUJE', 'SUPERFICIE EMPUJE', 'NUM', 6, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'SUPERFICIE_FRICCION', 'SUPERFICIE FRICCION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'TIPO_COJINETES_EJES', 'TIPO COJINETES EJES', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'TOLERANCIA', 'TOLERANCIA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'DIAMETRO_EJE', 'DIAMETRO EJE', 'NUM', 6, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'ESFUERZO_TORQUE_NOMINAL', 'ESFUERZO TORQUE NOMINAL', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'NUMERO_DE_SECCIONES', 'NUMERO DE SECCIONES', 'NUM', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'NUMERO_COJINETES_DE_EMPUJE', 'NUMERO COJINETES DE EMPUJE', 'NUM', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COJINETES_EJES', 'NUMERO_COJINETES_DE_SOPORTE', 'NUMERO COJINETES DE SOPORTE', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'TIPO_COMPRESOR', 'TIPO COMPRESOR', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'TIPO_REFRIGERANTE', 'TIPO REFRIGERANTE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COMPRESORES', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COND_EVAP_INTERCAM', 'PRESION_DESCARGA_BAR', 'PRESION DESCARGA BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COND_EVAP_INTERCAM', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COND_EVAP_INTERCAM', 'TIPO_REFRIGERANTE', 'TIPO REFRIGERANTE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('COND_EVAP_INTERCAM', 'PRESION_SUCCION', 'PRESION SUCCION', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'CAPACIDAD_LUBRICANTE', 'CAPACIDAD DE LUBRICANTE', 'NUM', 7, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'EMPUJE_DE_LA_HELICE', 'EMPUJE DE LA HELICE', 'NUM', 6, 2, 'kN');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'POTENCIA_NOMINAL_HP', 'POTENCIA NOMINAL HP', 'NUM', 7, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'PRESION', 'PRESION', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'TIPO_ENGRANAJES', 'TIPO ENGRANAJES', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'VELOCIDAD_NOMINAL_ENTRADA_N1', 'VELOCIDAD_NOMINAL_ENTRADA_N1', 'NUM', 7, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'VELOCIDAD_NOMINAL_SALIDA_N2', 'VELOCIDAD NOMINAL SALIDA N2', 'NUM', 7, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('ENG_REDUCTORES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'AMPERAJE_PRIMARIO', 'AMPERAJE PRIMARIO', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'AMPERAJE_SECUNDARIO', 'AMPERAJE SECUNDARIO', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ESTABILIZACION_EN_ROLIDO', 'ESTABILIZACION EN ROLIDO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ESPACIAMIENTO_CANAL', 'Espaciamiento Canal', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ELEVACION_COVERTURA', 'Covertura de Elevacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'FRECUENCIA_TRANSMISION', 'FRECUENCIA TRANSMISION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'FASE', 'Fase', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'FRECUENCIA_OPERACION', 'Frecuencia Operacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'IMPEDANCIA_ANTENA', 'Impedancia antena', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'INTERMODULACION', 'Intermodulacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'MODULACION', 'Modulacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POTENCIA_DE_TRANSMISION', 'POTENCIA DE TRANSMISION', 'NUM', 4, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POTENCIA_DEL_MAGNETRON', 'POTENCIA DEL MAGNETRON', 'NUM', 5, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POTENCIA_DISIPADA', 'POTENCIA DISIPADA', 'NUM', 6, 2, 'W');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'PRF_CORTO', 'PRF CORTO', 'NUM', 4, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'PRF_LARGO', 'PRF LARGO', 'NUM', 4, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POTENCIA_SALIDA', 'Potencia de Salida', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'PULSO', 'Pulso', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'PRF', 'Prf', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'POLARIZACION', 'Polarizacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'RED', 'Red de Operacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'RPMS', 'RPMS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'RESPONSABLE', 'Responsable', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'RATA_ROTACION', 'Rata de Rotacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'RANGO_FRECUENCIA', 'Rango Frecuencia', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'SENSIBILIDAD', 'Sensibilidad', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'SECTOR_BLANKING', 'Sector Blanking', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'TIPO_DE_ANTENA', 'TIPO DE ANTENA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'TIPO_RADAR', 'TIPO RADAR', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'TIPO_DE_EQUIPO', 'TIPO DE EQUIPO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'USO', 'Uso', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'VOLTAGE_ALIMENTACION', 'Voltage Alimentacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'VELOCIDAD_ROTACION_ANTENA', 'VELOCIDAD ROTACION ANTENA', 'NUM', 5, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ANTENA_PARADA', 'ANTENA PARADA', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ANTENA_ROTACION', 'ANTENA DE ROTACION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ALGORITMO_ENCRIPCION', 'ALGORITMO_ENCRIPCION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'CONSUMO_POTENCIA', 'Consumo Potencia', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ESPECIALIDAD', 'Especialidad', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ALCANCE_MAXIMO', 'ALCANCE MAXIMO', 'NUM', 12, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ANCHO_DE_PULSO', 'ANCHO_DE_PULSO', 'NUM', 10, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'AZIMUTH', 'Azimuth', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'ELE_VACION', 'Elevacion', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'LONGITUD_DE_RADIADOR', 'LONGITUD DE RADIADOR', 'NUM', 4, 2, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'VOLTAJE_DC', 'VOLTAJE DC', 'NUM', 4, 0, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'NO_CANALES', 'NUMERO DE CANALES', 'NUM', 15, 0, 'UN');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'CLAVES', 'CLAVES O LLAVES', 'NUM', 4, 0, 'UN');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'MODO_OPERACION', 'MODO DE OPERACION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'CANALES', 'CANALES', 'NUM', 10, 0, 'UN');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'BANDA', 'BANDA DE OPERACION', 'CHAR', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'DESVIACION', 'DESVIACION DE FRECUENCIA', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECT_RADAR_COM', 'UNIDAD_DE_ASIGNACIOM', 'UNIDAD DE ASIGNACION', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'DIAMETRO_EJE', 'DIAMETRO EJE', 'NUM', 6, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'CLASE_PROTECCION', 'CLASE DE PROTECCION', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'REF_RODAMIENTO', 'REFERENCIA DE RODAMIENTO', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'TIPO_DE_EQUIPO', 'TIPO DE EQUIPO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'POTENCIA_HP', 'POTENCIA HP', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_ELECTRIC_TALLER', 'POTENCIA_HP', 'POTENCIA HP', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'CAPACIDAD_BTUH', 'CAPACIDAD_BTUH', 'NUM', 9, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'NUMERO_DE_CILINDROS', 'NUMERO_DE_CILINDROS', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'TIPO_COMPRESOR', 'TIPO COMPRESOR', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'TIPO_REFRIGERANTE', 'TIPO REFRIGERANTE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_REFRIGER', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'PRESION_MAX', 'PRESION MAXIMA DE TRABAJO', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'AGENTE_EXTINTOR_ABC', 'AGENTE EXTINTOR ABC', 'CHAR', 12, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'CAPACIDAD_LIBRAS', 'CAPACIDAD EN LIBRAS', 'NUM', 7, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'CAPACIDAD_LITROS', 'CAPACIDAD EN LITROS', 'NUM', 8, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'CAUDAL_LPM', 'CAUDAL EN l/min', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'GAS_PROPULSION', 'GAS PROPULSION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'LONG_DE_DISPARO', 'LONGITUD DE DISPARO', 'NUM', 5, 0, 'm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'PRESION_DE_PRUEBA_BAR', 'PRESION DE PRUEBA_BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'PRESION_DESCARGA_BAR', 'PRESION DESCARGA BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'PRESION_DESCARGA_PSI', 'PRESION DESCARGA PSI', 'NUM', 6, 2, 'psi');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'TIPO_EXTINTOR', 'TIPO EXTINTOR', 'CHAR', 15, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('EQ_RESP_BOT_EXTINT', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'CLASE_AISLAMIENTO', 'CLASE DE AISLAMIENTO', 'CHAR', 8, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'CLASE_PROTECCION', 'CLASE DE PROTECCION', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'FACTOR_DE_POTENCIA', 'FACTOR DE POTENCIA', 'NUM', 4, 2, '%');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'POTENCIA_HP', 'POTENCIA HP', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'REF_RODAMIENTO', 'REFERENCIA DE RODAMIENTO', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'TEMPERATURA_AMBIENTE', 'TEMPERATURA AMBIENTE', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'TIPO_AMORTIGUACION', 'TIPO AMORTIGUACION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GENERADORES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'CAUDAL_M3H', 'CAUDAL EN m3/h', 'NUM', 6, 2, 'm3/h');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('GRUP_VENT_BLOWER', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'DIAMETRO_HELICE', 'DIAMETRO HELICE', 'NUM', 7, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'DIAMETRO_NUCLEO', 'DIAMETRO NUCLEO', 'NUM', 5, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'NUMERO_DE_PALAS', 'NUMERO DE PALAS', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'TIPO_HELICE', 'TIPO HELICE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('HELICES', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'CAPACIDAD_LUBRICANTE', 'CAPACIDAD DE LUBRICANTE', 'NUM', 7, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'CARRERA_DEL_PISTON', 'CARRERA DEL PISTON', 'NUM', 5, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'CICLO_TRABAJO', 'CICLO DE TRABAJO', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'DIAMETRO_CILINDRO', 'DIAMETRO CILINDRO', 'NUM', 6, 2, 'mm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'FECHA_ULTIMO_MANTTO', 'FECHA ULTIMO MANTTO', 'DATE', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'INYECCION', 'INYECCION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'NUMERO_DE_CILINDROS', 'NUMERO_DE_CILINDROS', 'NUM', 2, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'PRESION_DE_AIRE_ARRANQUE', 'PRESION DE AIRE ARRANQUE', 'NUM', 6, 2, 'psi');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'RELACION_DE_COMPRESION', 'RELACION DE COMPRESION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'SISTEMA_ARRANQUE', 'SISTEMA ARRANQUE', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'SISTEMA_ENFRIAMIENTO', 'SISTEMA ENFRIAMIENTO', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'TIPO_ACEITE', 'TIPO_ACEITE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'TIPO_MOTOR', 'TIPO MOTOR', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'POTENCIA_HP', 'POTENCIA HP', 'NUM', 6, 2, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_DIESEL', 'PLANO_NUMERO', 'Plano Numero', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'TEMPERATURA_AMBIENTE', 'TEMPERATURA AMBIENTE', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'TIPO_ACOPLE', 'TIPO ACOPLE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'TIPO_CORRIENTE', 'Tipo de corriente', 'CHAR', 10, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_ELECTRICOS', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'SENTIDO_GIRO', 'SENTIDO GIRO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'SISTEMA_ARRANQUE', 'SISTEMA ARRANQUE', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'SISTEMA_DE_INCLINACION', 'SISTEMA DE INCLINACION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'SISTEMA_LUBRICACION', 'SISTEMA LUBRICACION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'TIPO_ACEITE', 'TIPO_ACEITE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'TIPO_MOTOR', 'TIPO MOTOR', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'FAMILIA', 'FAMILIA MOTOR F/B', 'NUM', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'ESTADO_RODAJE_INICIAL', 'EST. RODAJE INICIAL MOTOR F/B', 'CHAR', 15, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'USUARIO_GEN_REPORTE', 'USUARIO GENERADOR REPORTE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('MOTORES_FUERA_BOR', 'PLANO_NUMERO', 'Plano Numero', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'CAUDAL_M3H', 'CAUDAL EN m3/h', 'NUM', 6, 2, 'm3/h');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PLANTA_TRATAMIENTO', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'PRESION_DESCARGA_BAR', 'PRESION DESCARGA BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'PRESION_SUCCION', 'PRESION SUCCION', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'RPM', 'RPM', 'NUM', 9, 2, 'rpm');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'TIPO_PURIFICADORES', 'TIPO PURIFICADORES', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'CAUDAL_M3H', 'CAUDAL EN m3/h', 'NUM', 6, 2, 'm3/h');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('PURIFICADORES', 'TIPO_DE_FLUIDO', 'TIPO DE FLUIDO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'AMPERAJE', 'AMPERAJE', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'TEMPERATURA_TRABAJO', 'TEMPERATURA TRABAJO', 'NUM', 5, 2, '°C');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'VOLTAJE_DC', 'VOLTAJE DC', 'NUM', 4, 0, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'CLASE_PROTECCION', 'CLASE DE PROTECCION', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TABLERO_ELECTRICO', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'CAPACIDAD_LITROS', 'CAPACIDAD EN LITROS', 'NUM', 8, 2, 'l');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'PRESION_DESCARGA_BAR', 'PRESION DESCARGA BAR', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'TIPO_MONTAJE', 'TIPO MONTAJE', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TANQUES', 'TIPO_DE_FLUIDO', 'TIPO DE FLUIDO', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'AMPERAJE_PRIMARIO', 'AMPERAJE PRIMARIO', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'AMPERAJE_SECUNDARIO', 'AMPERAJE SECUNDARIO', 'NUM', 6, 2, 'A');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'CALIBRE_ALAMBRE', 'CALIBRE ALAMBRE', 'CHAR', 5, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'CLASE_AISLAMIENTO', 'CLASE DE AISLAMIENTO', 'CHAR', 8, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'CLASE_PROTECCION', 'CLASE DE PROTECCION', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'FRECUENCIA', 'FRECUENCIA', 'NUM', 5, 2, 'hz');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'FUSIBLE_DE_PROTECCION', 'FUSIBLE DE PROTECCION', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'MANUALES_TECNICOS', 'MANUALES TECNICOS', 'CHAR', 30, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'NUMERO_ESPIRAS_PRIMARIO', 'NUMERO ESPIRAS PRIMARIO', 'NUM', 3, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'POTENCIA_KW', 'POTENCIA EN Kw', 'NUM', 7, 2, 'kw');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'PROTECCION_ANTICHOQUE', 'PROTECCION ANTICHOQUE', 'CHAR', 25, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'TIPO_DE_CONEXION', 'TIPO DE CONEXION', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'TOLERANCIA_EN_PORCENTAJE', 'TOLERANCIA EN PORCENTAJE', 'NUM', 5, 2, '%');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'VOLTAJE_PRIMARIO', 'VOLTAJE PRIMARIO', 'NUM', 4, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'VOLTAJE_SECUNDARIO', 'VOLTAJE SECUNDARIO', 'NUM', 4, 0, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('TRANSFORMADORES', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VALVULAS', 'VOLTAJE_DC', 'VOLTAJE DC', 'NUM', 4, 0, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VALVULAS', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VALVULAS', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VALVULAS', 'PRESION_SUCCION', 'PRESION SUCCION', 'NUM', 6, 2, 'bar');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VENTILAD_EXTRACTOR', 'VOLTAJE', 'Voltaje', 'NUM', 6, 2, 'V');
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VENTILAD_EXTRACTOR', 'CONTROL_VIDA_UTIL', 'CONTROL VIDA UTIL', 'CHAR', 28, 0, NULL);
INSERT INTO clases (clase, caracteristica, denominacion, tipo_campo, ctd_posiciones, decimales, unidad) VALUES ('VENTILAD_EXTRACTOR', 'TIPO_MATERIAL', 'TIPO MATERIAL', 'CHAR', 20, 0, NULL);
